"""empty message

Revision ID: 1176bba2445b
Revises: 64e393ce9419
Create Date: 2016-08-30 21:20:21.029270

"""

# revision identifiers, used by Alembic.
revision = '1176bba2445b'
down_revision = '64e393ce9419'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
