"""empty message

Revision ID: 59e08b73f62d
Revises: 4ef4f9095882
Create Date: 2016-09-02 17:51:29.316589

"""

# revision identifiers, used by Alembic.
revision = '59e08b73f62d'
down_revision = '4ef4f9095882'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_column('comments', 'disable')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disable', sa.BOOLEAN(), nullable=True))
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
