"""empty message

Revision ID: 5a579aefb68e
Revises: 8091ca314c2e
Create Date: 2016-08-29 16:04:38.554825

"""

# revision identifiers, used by Alembic.
revision = '5a579aefb68e'
down_revision = '8091ca314c2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
